### ISSUE TITLE
setup.py now imports setuptools

### ISSUE THREAD

**Issue by ilanschnell** [blaze/datashape#182]
Why is setuptools now required inside setup.py?  Using setuptools make packages much harder to build.  I would much rather prefer setuptools not being used.  Thanks.

**Comment by llllllllll** [comment]
This was used so that people can do `setup.py develop`. What does setuptools make more difficult?

**Comment by ilanschnell** [comment]
When you use `setuptools`, all the install requirements need to installed at build time, because otherwise setuptools will try to fetch them on the fly, which is not what we want (at least not when building conda packages).  Also setuptools always tried to create `.egg` directories in `site-packages`, which are problematic because their path needs to be added to `easy-install.pth`.  From my perspective setuptools is the source of almost all packaging problems Python is suffering from.

Having `conda-build` installed, you can say:
```
$ conda develop
```

**Comment by llllllllll** [comment]
I don't think there have been any issues with the conda builds for blaze, datashape or odo. Also, not everyone uses conda.

**Comment by ilanschnell** [comment]
But everyone should be using conda :-)  Anyway, if you want to use setuptools, that ok (I guess).  I personally avoid it like the plague.
