### ISSUE TITLE
Tests fail using Python 3.6

### ISSUE THREAD

**Issue by ilanschnell** [blaze/datashape#221]
Running datashape `0.5.2` against Python 3.6rc2 (64-bit Linux).  I get:
```======================================== FAILURES ========================================
_______________________ [doctest] datashape.internal_utils.groupby _______________________
Expected:
    {3: ['Bob', 'Dan'], 5: ['Alice', 'Edith', 'Frank'], 7: ['Charlie']}
Got:
    {5: ['Alice', 'Edith', 'Frank'], 3: ['Bob', 'Dan'], 7: ['Charlie']}
```

**Comment by skrah** [comment]
@ilanschnell I just fixed it in master.  Do you need the fix in 0.5.2, too?

**Comment by ilanschnell** [comment]
Thanks for fixing it.  How do you fix it in 0.5.2 retrospectively?  I would suggest to release a new version which includes the fix.

**Comment by skrah** [comment]
You're right, of course there is a released tarball already for 0.5.2 (and also for 0.5.3).  I guess the new version will be 0.5.4.

**Comment by skrah** [comment]
I just tagged and pushed the release, Travis-CI looks good with Python 3.6.

**Comment by ilanschnell** [comment]
Thanks, I'll give it a try.
