### ISSUE TITLE
RecursionError when using discover() on SQL tables with circular references

### ISSUE THREAD

**Issue by riosv** [blaze/datashape#226]
Hi,

Suppose two tables in a PostgreSQL DB with the following DDL:

``` 
CREATE TABLE store (
store_id integer CONSTRAINT store_pkey PRIMARY KEY,
manager_staff_id smallint NOT NULL);


CREATE TABLE staff (
    staff_id integer CONSTRAINT staff_pkey PRIMARY KEY,
    first_name character varying(45) NOT NULL,
    last_name character varying(45) NOT NULL,
    store_id smallint NOT NULL);

ALTER TABLE ONLY store
    ADD CONSTRAINT store_manager_staff_id_fkey FOREIGN KEY (manager_staff_id) REFERENCES staff(staff_id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ONLY staff
    ADD CONSTRAINT staff_store_id_fkey FOREIGN KEY (store_id) REFERENCES store(store_id);
```

As you can see, each table references the other's pk. The following code causes a `RecursionError`. Seems like `discover()` is caught in an infinite loop trying to generate the datashape element for the tables.

```
from odo import resource
from datashape import discover

store = resource('postgresql://user:pwd@localhost/db::store')
discover(store)
```

**Comment by llllllllll** [comment]
hmm, with the way pks work in datashape I am not sure how this would work. Right now a pk creates a map type and this would require the datashape object to be lazily constructed. What do you expect the output do be?

**Comment by riosv** [comment]
I think the datashapes should be:
```
# Staff
var * {
  staff_id: int32,
  first_name: string[45],
  last_name: string[45],
  store_id: map[int32, {store_id: int32, manager_staff_id: int32}]
}

# Store
var * {
    store_id: int32,
    manager_staff_id: map[int32, {
        staff_id: int32,
        first_name: string[45],
        last_name: string[45],
        store_id: int32
    }
}
```
So the discovery of foreign pk should stop when it reaches the parent table.

**Comment by llllllllll** [comment]
It seems weird to have two representations for the same table in one dshape. I think it would probably be best to have `follow_fkey=False` instead to solve these cycles.

Also, this issue is actually with odo, not datashape itself. I reposted the issue here: https://github.com/blaze/odo/issues/539 and we can continue discussion there.
