### ISSUE TITLE
Need to clarify details of type constructor keyword parameters

### ISSUE THREAD

**Issue by mwiebe** [blaze/datashape#26]
As we've written the description of keyword arguments so far, it's implicitly following Python's approach because of the current implementation in the parser. This is not the only option, and not necessarily the best way to do things for datashape.

The main purpose of having keyword arguments in the type constructors is documentation. Consider variations of a `bytes` type:

```
bytes
bytes[8]
bytes[8,4]
bytes[align=4]
bytes[8, align=4]
bytes[size=8]
bytes[size=8, align=4]
bytes[align=4, size=8]
```

Some things that need to be made clear:
* Is it ok to provide keyword arguments an any order, or should we always require a fixed order?
* Do we allow a given parameter to be provided either with a keyword or not?
* If things are in a fixed order, do we allow a positional argument after a keyword argument?

An example possibility is to have dimension constructors be syntactic sugar as follows:

```
dim[arg1, argname2=arg2] * int32
  equivalent to
dim[arg1, argname2=arg2, int32]
```

My inclination is towards the following, based on wanting the representation of a given type to not have too many possibilities, and to aid parsing efficiency in static languages:

* Require argument order to always match up.
* Require keyword name if it is a keyword argument.
* Allow non-keyword arguments after keyword arguments.

For the `bytes` example above, the type constructor signatures we get are:

```
# variable-sized bytes type
bytes
# fixed-size bytes type of a given size, alignment 1
bytes[<int>]
# variable-sized bytes type, with given alignment
bytes[align=<int>]
# fixed-size bytes type, with given alignment
bytes[<int>, align=<int>]
```

**Comment by kwmsmith** [comment]
Closing this issue due to time lag, and due to other datashape activity in DyND itself.
