### ISSUE TITLE
coercion/overloading mechanism is not sound

### ISSUE THREAD

**Issue by mwiebe** [blaze/datashape#7]
I'm getting some weird results with the coercion and overloading, where coercions are flipping sometimes.

For example as tested,
int -> float64 should be preferred over int -> complex[float32]

```
        a, b, c = dshapes('int32', 'float64', 'complex[float32]')
        self.assertLess(coercion_cost(a, b), coercion_cost(a, c))
```

but, after adding another test checking a related overloading, this flipped so that the conversion to complex[float32] was preferred.

The implementation takes what is a a partial ordering of types, and a type promotion lattice defined based on that, and smushes it onto the real line. Is there good precedent for this approach to the problem?

**Comment by cpcloud** [comment]
is this code being using anymore?

**Comment by cpcloud** [comment]
cc @mwiebe

**Comment by mwiebe** [comment]
@cpcloud would you be able to delete https://github.com/ContinuumIO/datashape/blob/master/datashape/coercion.py and still have everything work?

**Comment by cpcloud** [comment]
this code has been removed
