### ISSUE TITLE
Discover Python int as int32 instead of int64

### ISSUE THREAD

**Issue by mrocklin** [blaze/datashape#95]
Should we default to `int32` for basic Python ints?  This is more compatible with DyND and, I think, CPython itself. 

### Current Behavior

```Python
>>> discover(1)
ctype("int64")
```

### Proposed Behavior

```Python
>>> discover(1)
ctype("int32")
```

cc @mwiebe

**Comment by mwiebe** [comment]
Relevant bikeshedding: https://github.com/rust-lang/rfcs/blob/master/text/0544-rename-int-uint.md

**Comment by kwmsmith** [comment]
I'm +1 on using `int64` here in all instances (the current behavior).  @mrocklin @izaid if you have further thoughts, please re-open this thread.
